/**
 * The manifest, against what the community directory actually requires.
 *
 * This file is not decoration. The directory processes `manifest.json` at the
 * HEAD of the default branch, and Obsidian downloads the release whose tag
 * matches its `version`. So a wrong value here is not a lint failure, it is a
 * plugin nobody can install, discovered after publishing rather than before.
 *
 * The rules asserted below are the ones the directory states outright:
 * required fields, an `id` that is unique and free of "obsidian", a semver
 * `version` the release tag has to match, and `isDesktopOnly` which must be
 * true if any Node or Electron API is used. It is false here, and the bundle
 * check in `esbuild.config.mjs` is what keeps that honest.
 */

import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'))

test('the manifest lives at the repository root, where the directory reads it', () => {
  // Not `plugin/manifest.json`. The copy beside main.js is generated by the
  // build; this is the one the directory and a human visitor both see first.
  assert.ok(manifest.id, 'no manifest at the repository root')
})

test('every field the directory requires is present', () => {
  for (const field of ['id', 'name', 'version', 'minAppVersion', 'description', 'author']) {
    assert.ok(manifest[field], `manifest is missing "${field}"`)
  }
  assert.equal(typeof manifest.isDesktopOnly, 'boolean', 'isDesktopOnly must be present and boolean')
})

test('the id is submittable', () => {
  // Stated by the directory: the id must be unique across published plugins and
  // cannot contain "obsidian". It is also the folder name under
  // .obsidian/plugins/, so changing it after release strands everyone's
  // data.json. That makes it the least changeable string in the project.
  assert.doesNotMatch(manifest.id, /obsidian/i, 'the id cannot contain "obsidian"')
  assert.match(manifest.id, /^[a-z0-9-]+$/, 'lowercase, digits and hyphens only')
})

test('the version is the x.y.z a release tag can match', () => {
  // Obsidian fetches the release tagged with exactly this version. Anything the
  // release workflow cannot reproduce as a tag makes the plugin uninstallable.
  assert.match(manifest.version, /^\d+\.\d+\.\d+$/, 'versions are supported only as x.y.z')
})

test('the name does not claim to be first-party, or repeat itself', () => {
  // The trademark rule is about the word "Obsidian", not about resembling any
  // particular Obsidian product, and "Plugin" in a name is redundant. Both have
  // been enforced retroactively on plugins already in the directory.
  assert.doesNotMatch(manifest.name, /obsidian/i, 'do not use the Obsidian trademark in the name')
  assert.doesNotMatch(manifest.name, /\bplugins?\b/i, '"Plugin" in the name is duplication')
})

test('isDesktopOnly is false, which is a claim about the code', () => {
  // Only true if the plugin uses a Node or Electron API. It uses none, and
  // esbuild marks them external so an accidental import fails the build loudly
  // rather than shipping a shim. If that ever changes, this has to change with
  // it, because the directory treats it as a correctness requirement.
  assert.equal(manifest.isDesktopOnly, false)
})
