// Generated by Open Publish on every build from the published snapshot.
// Do not edit. Your changes will be overwritten. Change these in Obsidian,
// under Settings -> Open Publish -> Site options.
//
// This committed copy is the fallback used before the first publish, so that a
// fresh clone type-checks and builds. It must list every option with a sensible
// default: `fetch-content.mjs` merges the snapshot over these, so an older
// snapshot missing a key gets the default rather than `undefined`.
export const site = {
  title: 'My Notes',
  homepage: '',
  locale: 'en-US',
  dir: 'ltr',
  noIndex: false,
  showThemeToggle: true,
  strictLineBreaks: false,
  showNavigation: true,
  showSearch: true,
  showGraph: true,
  showOutline: true,
  showBacklinks: true,
  showTags: true,
  showPageMetadata: false,
  /**
   * Read by nothing here, and that is deliberate rather than an omission.
   * Quartz has no previous/next component, so this starter has nothing to
   * honour the intent with. Site options are intent, not layout
   * (`docs/architecture.md`), so it is carried and ignored, and a future
   * starter that does have one gets the answer without a plugin change.
   */
  showPrevNext: true,
  /**
   * Sidebar order and hidden pages, both empty until somebody arranges them in
   * Obsidian. Slugs, not vault paths, and a folder is named by the slug of its
   * index page: `notes/index` for the folder published at `/notes`.
   */
  nav: { order: [], hidden: [] },
  analytics: { provider: 'none', id: '' },
}
export default site
